name: Examples Release Manager

on:
  # ignore for now, how would open source get  eamHubSpec/tested versions? would we make this a single input where you paste json, multiple with versions?
  workflow_dispatch:
    inputs:
      versionFileJSON:
          description: 'The file with all the versions' 
          required: true
          type: string

  # repository_dispatch:
  #   types: [release-trigger]

env:
  # Variables to control GH CLI
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  GH_HOST: github.com

jobs:
  release:
    runs-on: ubuntu-20.04

    environment: release_environment

    steps:
      - name: Create Tested Versions File
        run: |
          mkdir $RUNNER_TEMP/version_file && cd $RUNNER_TEMP/version_file
          echo -e "${{ github.event.inputs.versionFileJSON }}" > openhorizon-tested-versions.txt
        shell: bash
      
      - name: Create Release
        run: |
          gh release create v${AGBOT_VERSION} \
            ${RUNNER_TEMP}/version_file/openhorizon-tested-versions.txt \
            -t "v${AGBOT_VERSION}" \
            --target 6d8c2cdff52dd519cb4e453f3a6c63186a6ba2d7
        shell: bash
        env:
          AGBOT_VERSION: ${{ fromJSON(github.event.inputs.versionFileJSON).amd64_agbot }}